---
# tasks file for awx_k8s_install
- name: Install make
  ansible.builtin.package:
    name: make
    state: latest

- name: Git checkout AWX-Operator
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx-operator.git'
    dest: ~/awx-operator
    version: "{{ awxoperater_version }}"

- name: Set Namespace
  shell: export NAMESPACE=awx

- name: Make deploy
  make:
    chdir: ~/awx-operator
    target: deploy

- name: Copy deploy template
  ansible.builtin.template:
    src: deploy.yml.j2
    dest: ~/deploy.yml

- name: Copy secret template
  ansible.builtin.template:
    src: secret.yml.j2
    dest: ~/secret.yml

- name: Copy ingress template
  ansible.builtin.template:
    src: ingress.yml.j2
    dest: ~/ingress.yml

- name: Config and run AWX
  shell: kubectl apply -f ~/secret.yml -f ~/deploy.yml -f ~/ingress.yml
